---
{
  apiVersion: "cert-manager.io/v1",
  kind: "Certificate",
  metadata: {
    name: "prometheus-tls",
    namespace: "observability",
  },
  spec: {
    secretName: "prometheus-tls",
    issuerRef: {
      name: "vault-issuer",
      kind: "ClusterIssuer",
    },
    dnsNames: [
      "kube-prometheus-stack-prometheus",
      "kube-prometheus-stack-prometheus.observability",
      "kube-prometheus-stack-prometheus.observability.svc",
      "kube-prometheus-stack-prometheus.observability.svc.cluster.local",
      "prometheus-operated",
      "prometheus-operated.observability",
      "prometheus-operated.observability.svc",
      "prometheus-operated.observability.svc.cluster.local",
    ],
    usages: [
      "server auth",
    ],
  },
}
---
{
  apiVersion: "cert-manager.io/v1",
  kind: "Certificate",
  metadata: {
    name: "alertmanager-tls",
    namespace: "observability",
  },
  spec: {
    secretName: "alertmanager-tls",
    issuerRef: {
      name: "vault-issuer",
      kind: "ClusterIssuer",
    },
    dnsNames: [
      "kube-prometheus-stack-alertmanager",
      "kube-prometheus-stack-alertmanager.observability",
      "kube-prometheus-stack-alertmanager.observability.svc",
      "kube-prometheus-stack-alertmanager.observability.svc.cluster.local",
      "alertmanager-operated",
      "alertmanager-operated.observability",
      "alertmanager-operated.observability.svc",
      "alertmanager-operated.observability.svc.cluster.local",
    ],
    usages: [
      "server auth",
    ],
  },
}
