---
# yaml-language-server: $schema=https://51f35e2d.kubernetes-schemas-9iu.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
{
  apiVersion: "helm.toolkit.fluxcd.io/v2",
  kind: "HelmRelease",
  metadata: {
    name: "brrpolice",
  },
  spec: {
    chartRef: {
      kind: "OCIRepository",
      name: "brrpolice",
    },
    interval: "1h",
    values: {
      controllers: {
        brrpolice: {
          containers: {
            app: {
              image: {
                repository: "ghcr.io/d4rkfella/brrpolice",
                tag: "0.14.0@sha256:37399cb87f00c10a3c908d891ab0b59cc84e768d903cb6295bdd22e61ad81714",
              },
              env: {
                BRRPOLICE_HTTP__PORT: 80,
                BRRPOLICE_LOGGING__LEVEL: "info",
                BRRPOLICE_QBITTORRENT__BASE_URL: "http://qbittorrent.media.svc.cluster.local",
                TZ: "Europe/Sofia",
              },
              probes: {
                liveness: {
                  enabled: true,
                  spec: {
                    periodSeconds: 30,
                    timeoutSeconds: 5,
                    failureThreshold: 5,
                  },
                },
                readiness: {
                  enabled: true,
                  custom: true,
                  spec: {
                    httpGet: {
                      path: "/readyz",
                      port: 80,
                    },
                    initialDelaySeconds: 0,
                    periodSeconds: 10,
                    timeoutSeconds: 5,
                    failureThreshold: 3,
                  },
                },
              },
              securityContext: {
                allowPrivilegeEscalation: false,
                readOnlyRootFilesystem: true,
                capabilities: {
                  drop: [
                    "ALL",
                  ],
                },
              },
              resources: {
                requests: {
                  cpu: "10m",
                },
                limits: {
                  memory: "128Mi",
                },
              },
            },
          },
        },
      },
      defaultPodOptions: {
        securityContext: {
          runAsNonRoot: true,
          runAsUser: 65532,
          runAsGroup: 65532,
          fsGroup: 65532,
          fsGroupChangePolicy: "OnRootMismatch",
        },
      },
      service: {
        app: {
          ports: {
            http: {
              port: 80,
            },
          },
        },
      },
      serviceMonitor: {
        app: {
          endpoints: [{
            port: "http",
          }],
        },
      },
      persistence: {
        data: {
          existingClaim: "{{ .Release.Name }}",
        },
      },
    },
  },
}
