---
{
  apiVersion: "kustomize.config.k8s.io/v1beta1",
  kind: "Kustomization",
  resources: [
    # renovate: datasource=github-releases depName=kubevirt/common-templates
    "https://github.com/kubevirt/common-templates/releases/download/v0.34.1/common-templates-amd64-v0.34.1.yaml",
  ],
}
