---
{
  # yaml-language-server: $schema=https://51f35e2d.kubernetes-schemas-9iu.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
  apiVersion: "helm.toolkit.fluxcd.io/v2",
  kind: "HelmRelease",
  metadata: {
    name: "filestash",
  },
  spec: {
    interval: "1h",
    chartRef: {
      kind: "OCIRepository",
      name: "filestash",
    },
    values: {
      controllers: {
        filestash: {
          annotations: {
            reloader.stakater.com/auto: "true",
          },
          initContainers: {
            init-branding: {
              image: {
                repository: "alpine",
                tag: 3.19,
              },
              command: [
                "sh",
                "-c",
              ],
              args: [
                "\
                   wget -O /branding/branding-desktop.css https://gist.githubusercontent.com/mickael-kerjean/bc1f57cd312cf04731d30185cc4e7ba2/raw/d706dcdf23c21441e5af289d871b33defc2770ea/destop.css\n\
                  ",
              ],
              securityContext: {
                allowPrivilegeEscalation: false,
                readOnlyRootFilesystem: true,
                runAsNonRoot: true,
                runAsUser: 65532,
                capabilities: {
                  drop: [
                    "ALL",
                  ],
                },
              },
            },
          },
          containers: {
            filestash: {
              image: {
                repository: "machines/filestash",
                tag: "latest",
              },
              env: {
                APPLICATION_URL: "filestash.darkfellanetwork.com",
                CANARY: "true",
                OFFICE_URL: "http://127.0.0.1:9980",
                OFFICE_FILESTASH_URL: "https://filestash.darkfellanetwork.com",
                OFFICE_REWRITE_URL: "https://office.darkfellanetwork.com",
              },
              securityContext: {
                allowPrivilegeEscalation: false,
                readOnlyRootFilesystem: true,
                runAsNonRoot: true,
                runAsUser: 1000,
                capabilities: {
                  drop: [
                    "ALL",
                  ],
                },
              },
            },
            collabora: {
              image: {
                repository: "collabora/code",
                tag: "25.04.9.4.1",
              },
              env: {
                extra_params: "--o:ssl.enable=false --o:ssl.termination=true --o:security.capabilities=false",
                aliasgroup1: "https://filestash.darkfellanetwork.com:443,https://office.darkfellanetwork.com:443",
              },
              securityContext: {
                "<<": {
                  allowPrivilegeEscalation: false,
                  readOnlyRootFilesystem: true,
                  runAsNonRoot: true,
                  runAsUser: 1000,
                  capabilities: {
                    drop: [
                      "ALL",
                    ],
                  },
                },
                runAsUser: 100,
              },
            },
          },
        },
      },
      defaultPodOptions: {
        securityContext: {
          runAsNonRoot: true,
          fsGroup: 100,
          fsGroupChangePolicy: "OnRootMismatch",
          seccompProfile: {
            type: "RuntimeDefault",
          },
        },
      },
      service: {
        filestash: {
          controller: "filestash",
          ports: {
            http: {
              port: 8334,
            },
          },
        },
        collabora: {
          controller: "filestash",
          ports: {
            http: {
              port: 9980,
            },
          },
        },
      },
      route: {
        filestash: {
          hostnames: [
            "filestash.darkfellanetwork.com",
          ],
          parentRefs: [{
            name: "internal",
            namespace: "envoy-gateway-system",
            sectionName: "https",
          }],
          rules: [{
            backendRefs: [{
              name: "filestash",
              port: 8334,
            }],
          }],
        },
        collabora: {
          hostnames: [
            "office.darkfellanetwork.com",
          ],
          parentRefs: [{
            name: "internal",
            namespace: "envoy-gateway-system",
            sectionName: "https",
          }],
          rules: [{
            backendRefs: [{
              name: "filestash-collabora",
              port: 9980,
            }],
          }],
        },
      },
      persistence: {
        state: {
          type: "persistentVolumeClaim",
          suffix: "state",
          size: "15Gi",
          accessMode: "ReadWriteOnce",
          storageClass: "openebs-zfs-128k",
          advancedMounts: {
            filestash: {
              filestash: [{
                path: "/app/data/state/",
              }],
            },
          },
        },
        branding: {
          type: "emptyDir",
          advancedMounts: {
            filestash: {
              init-branding: [{
                path: "/branding",
              }],
              collabora: [{
                path: "/usr/share/coolwsd/browser/dist/branding-desktop.css",
                subPath: "branding-desktop.css",
              }],
            },
          },
        },
        tmp: {
          type: "emptyDir",
          advancedMounts: {
            filestash: {
              filestash: [{
                path: "/tmp",
              }],
              collabora: [{
                path: "/tmp",
              }, {
                path: "/opt/collaboraoffice/var/cache",
              }, {
                path: "/opt/cool/child-roots",
              }],
            },
          },
        },
      },
    },
  },
}
