---
# yaml-language-server: $schema=https://51f35e2d.kubernetes-schemas-9iu.pages.dev/cert-manager.io/certificate_v1.json
{
  apiVersion: "cert-manager.io/v1",
  kind: "Certificate",
  metadata: {
    name: "buildkit-client",
  },
  spec: {
    secretName: "buildkit-client-tls",
    duration: "24h",
    privateKey: {
      algorithm: "ECDSA",
      encoding: "PKCS8",
      rotationPolicy: "Always",
      size: 256,
    },
    issuerRef: {
      name: "vault-issuer",
      kind: "ClusterIssuer",
      group: "cert-manager.io",
    },
    commonName: "buildkit-client",
    usages: [
      "client auth",
    ],
  },
}
