---
{
  apiVersion: "v1",
  kind: "Secret",
  metadata: {
    name: "gcp-kms-creds",
  },
  type: "Opaque",
  stringData: {
    openbao-unseal-creds.json: "ENC[AES256_GCM,data:e56wUeafTpKJuq0qk7TJjgAorqBnFZrTW4uV0VJUPd6rwh5Br7NyXA8lF10JzHw/tO1rqSrciA2E00aUh3zl4SVxTaNkaQwez0T1fYHscY5ObYkxI4i+5YR51kQE3+8A/Ba3ycpYhXeM+Fq2VItWP4jRPOsVhimx2VMso6/jdlYxY/DmgftnBeKEuiodVYcAZYvviMu+tmPrK2ggLiC+oUKFk9XSi3kMjvomW/S/0SKVpoeFnq3IcZn1yGmOH48UuKfxuR92NFiJdwMJxFbPYjrCAtTW/5FgOVvTEMPD2Y1E6ioJCTkFboB8iwCyDrCqQi0XeP2faz0N96MNq/ULQwgdYEXk4+F/a9AkEONwtu27fy02RTnIg1XnS9d8HEePTCJ6oDSFWpJdbGLX7jVEssha1xAlOhOP1x0Ezou/cxhbDwpsbgeasJNokrHjAmqNt0ToWadXv1xkZuyrUS0FCD/csYSMu8sUssY4joUTrRuqswiTNm7FXQtYi3paOZcJH1euO2/RVO8aqj1KhDsPFfSO6Heqls+p8DnA/W2Z9q4JrUNWVfbI7HiRVFFiLeLitP8gjhZFlP5mU6C0Pam/JENc2l/v78jla0CPV1etZenezZKHFTUOuso/W821Dl/kmAG73BNYdOuY4GjXhfawYXg88OCXC80Mp8XSpxgjTlMlVK9BErhcOKkDIpWgZk7BoO/vAd4Lb1kt2+wRD32VA2e+tq3KvnsvBbMBVfJzGMBbtna67IMWNmMSGGpiTIAgv3VSnZnR3LZrHNnHe/XjCX+dMMrK3vd9P3SA97fxqAoxXXQhRXtmLvUl8l7/gkR21rD/2IVqBfcm6BLT0EGBBJiqCGtwmGLwK7fFqdgv/Oq9gXKXbxJ/8xcFS+0hj3+tqIgmGK/5CF8wH2xjks1BGn2zBU7GkWAjFhAVZILxQOvgUQcjdNMvJjGcS4I+4qXhT79KLKc8y1Kc48ON1Kiy4bewJMAA5s0vdlyTFw70ZZzH2a6nsGyhef2Ty4K5pQfXfe+lkTz/G/XNFV0x/yOYjEjldsTO+zO7ORcSYwkKeBhIw1ExPVca42jCniQqnkafkgEh8S3Dx3sOhRW8VcdbrxmRWHVVNuppx1zvm4H9u+LHdFIRAcZMloD930kMihSRe4TxoogwU9u7SOkQS54MyIOgoabQz3LXrugTgLWtBlL5nSJHVn8oBsISLxSOk7wxp2CzsLFyLJ6qzKCHUyGiGbdlt98XaSIehiKehx0+lFFRJJ7ptqw6G5e7gdwYt3J5/55NYMbJIu67sejsLsl7Ig8EzVNhB3Gk8tzznMMOrpd+0sTDoKkcrBKiV5/dHfj1/TXZozkNmrCERxCfGcleT16T7WVuyx05cOXMl5qTbkz85deqs4YRcdp8In1kh6xOVtEbGkoNzRC4gsnD6jaU6RTJ5aY1BRHUN+gEqk1Nkl5i26Jit9nKcEUmIFAdygY0RbOqyQea8l0c6BdYIh0rOJYUxPMuDBjyz8fBIKXHNUTCKXekTqWFwNaozZxTC4O1HucRHSM6Sc4Edu0uuz9BVUts3d7TPGhqH3YNG8ARPnzIad5WCw2BRiWlTcbnFSFROXdIm+KOGZbokEFonaSSMbwGZNWFTNsxG0OiF88aZmQ80iuGaws31tquGu1ewrfKtpnwTJab12xtJejdPo51Hev9aczQ1Vy/nLSD/jtbP19S9m3/buFfq0G6OWxJ4oq9npfhdG7LDgUTCXMOBceEzW6hA1m3MfmYIfr0P+Ka3xpmGsJrrkSqTwCKgCS9N0z0z/tmUj/GZPQwl4lgKw437+CTPYmoO6JmeVa2ffAFojq6Fp+tXhRdRNd/U706LNwtwIK/D48SeSpKie7OWR2679iyLeIV5HsKo4rzRcRcvvH1wvyqMeClUAdFJfCMLbeqz04gaybwbRGQB5D/AlqtYBS6Emes92i7nIxjuyuusf2h81n6Jqk0M/e81DGRhglskWkuFVlc2iCJ3R+fHp9gWWe93QtXyelWI32u5Z0Vclm2tdyLEvDmdLDEH6AUkzbNXGYpikW0ziTLwgDbsfdWfNeSXAUilSF4zVRIwhthmM5TFREXl/UFt7MOj+e4r2PQPw1EBA/aRy1auY7MqeulaTb44cOm8bG8WSrRQkKXhsYrDJf2JgGOQCU0BokZnWorHThN4q0DQ8JVQy3T0ykFv5jkjAar/N3MhkAHAuIibdxQtcPYpcH4PXija7VQoNLeh0YxMcvnLFlg1vmZLA3yz9RzRkrZyUuQNGUc4iOLDIeSY9qjZPY8qvGMjsh19g7sEbkZm1GQMMN4uU9alS3hK23iQQAEy29QoxuA0xQLHRhw3E45jGe7g65tIEZjh5GWn5QDDuDJncuvtVZfliKw14lvQqWvDikHiLFllz00ZikVMOe4uMUOqggR4P+q/ZPWvgmjd9eiNqi5Kjrwh6htWkKfv5DcNzZVuonDLRv+8Z4/HXjciRCELeXMPAKgyUM1viXJJWjD23lK0JR0mjJ/Ld6wxk6wD/VqQV1NThYTbxs3dwTtmXE3Cc1ktOhFqh20OfCc2HnPW1LKzqwBEN4kcFgTSgxyBFCVbj0TnPYXyazW7ODSLf+CJEGrf6k60gJJZT2Z29VpoOnt9Rdo7SFFWFyh0rYH8YbEz+UuDsiVw+3+8ovJ7Aw2JkPw79ekvmlYckpTqYi70QWbmm57ek4FEtg74Pfh280yG+S0Z253vqb886WimGuM0/ew3HsccDAwaGajOWvSNcJSDEgvH2Qdaje7YACK6/0vVqs5L/AdjAfLrRoEPLLZbVp2/zbES0uHC2vSpG5VJS/s7Ux0+vYr0tL6wPlQCi7P41rJ9feiumHuSGBAA3mhtgjK2b/Y5opXLv+P2lSclpHr9ci2kbRMnHHgcCy2Fb+n2+j7EpOUSC1UoD1DYddfGP21CwYS4eOhOKEs81iDoy+gcE921krQ55RYDDQ4EBY1alI6bZO8IJQn1yvb/itCkBH0E92hFc2xEE31M6G2l5WgjIW281vbyB2lO/BKE7ikgS0Dk25ox19Q5JDHY1i7bPkgTM1HqP+3hXqCm+5UON9md6Qg+O1lasmaN85CimUKXvetQXVwql/47Cu7K9mjLfY537ZPhquDdOKs27ZhGDUmfCmCQbeztXnnqiOO,iv:XzDU+Vnpf3heRlLOdcRYDLIEsc77wC8lKmwJUyr3k3g=,tag:3TO1P8WS7bUoQ4eZFGGn0g==,type:str]",
  },
  sops: {
    age: [{
      enc: "\
         -----BEGIN AGE ENCRYPTED FILE-----\n\
         YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4bFZ0Q2JIQXpMRWk3Zng2\n\
         RStyU29mSUY2VFZQOVY3Y0Z5ajhGRzJ6UmpBCnRGZUFZM245dkd2N0Q0eWozNGZR\n\
         cUhNc3A2TGhEcDJQc3FHOGROaFZCdFEKLS0tIHArN2tFOVVlSEJwMWVzOXFiaTVr\n\
         ODVqM0ZVdGM3ZU51Vkl5RzJva0hMRjAK1R6EhNCBKvyYl0gI0ouaAtMMZ4BzOTb2\n\
         QhqVSIORyzmt71JLQNRV2BbQvrD3b+TRpedvCG41pGX/i18C2IV8Kg==\n\
         -----END AGE ENCRYPTED FILE-----\n\
        ",
      recipient: "age1frhtpr8u3u99pvcuq5mjevxdq9agjfpkd8fjtnpj9qymzh5v845q53f37d",
    }],
    encrypted_regex: "^(data|stringData)$",
    lastmodified: "2026-07-22T09:14:22Z",
    mac: "ENC[AES256_GCM,data:MLWNlm1m8pl9MmpaeRPONsW8uV8+wTwiK7PFznOgpFYo2mnSumHc4M9BcIrmSupl+9/85ykL0kosQ2Z0VZOXfWb1OF7rP8kY9CvX+OWfvPL9bGPFKbdXedqSZT27Lw1IQWdefxvGKeVXFZXksjKyQ8Wta0RL0rPZtYIInRteeNY=,iv:8xv8jVyPm59cPUxDBoEZ6PgUADofJoN9KT5uMWkIobU=,tag:qSp7b+tpR/cTapNIBgwtTQ==,type:str]",
    mac_only_encrypted: true,
    version: "3.13.2",
  },
}
---
{
  apiVersion: "v1",
  kind: "Secret",
  metadata: {
    name: "openbao-r2-credentials",
  },
  type: "Opaque",
  stringData: {
    AWS_ACCESS_KEY_ID: "ENC[AES256_GCM,data:oOw86nSJsgUkpAJPW8d2AD4WGQrsa41i6PkY9Sut2pA=,iv:4iqoaGxv38ttDqGqVGZ9V7kxvb0xt9iR6FNRccdwbxw=,tag:fFwHE+87F3n9RzmfShMLEQ==,type:str]",
    AWS_SECRET_ACCESS_KEY: "ENC[AES256_GCM,data:oB/ifRETqQYaW76O6wVgAj1dPApeNkTYWsr5VWLSAjNgIKLRPRW7XZ7VHu5Re6GKHD7RhxIIfj4LpQJLU7q8pg==,iv:4XXA8IxXFc/IWxazIBorLOA8lwgbDm436fuQlbejyiM=,tag:nWIkEvBkci57+TmL8eBSMQ==,type:str]",
  },
  sops: {
    age: [{
      enc: "\
         -----BEGIN AGE ENCRYPTED FILE-----\n\
         YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4bFZ0Q2JIQXpMRWk3Zng2\n\
         RStyU29mSUY2VFZQOVY3Y0Z5ajhGRzJ6UmpBCnRGZUFZM245dkd2N0Q0eWozNGZR\n\
         cUhNc3A2TGhEcDJQc3FHOGROaFZCdFEKLS0tIHArN2tFOVVlSEJwMWVzOXFiaTVr\n\
         ODVqM0ZVdGM3ZU51Vkl5RzJva0hMRjAK1R6EhNCBKvyYl0gI0ouaAtMMZ4BzOTb2\n\
         QhqVSIORyzmt71JLQNRV2BbQvrD3b+TRpedvCG41pGX/i18C2IV8Kg==\n\
         -----END AGE ENCRYPTED FILE-----\n\
        ",
      recipient: "age1frhtpr8u3u99pvcuq5mjevxdq9agjfpkd8fjtnpj9qymzh5v845q53f37d",
    }],
    encrypted_regex: "^(data|stringData)$",
    lastmodified: "2026-07-22T09:14:22Z",
    mac: "ENC[AES256_GCM,data:MLWNlm1m8pl9MmpaeRPONsW8uV8+wTwiK7PFznOgpFYo2mnSumHc4M9BcIrmSupl+9/85ykL0kosQ2Z0VZOXfWb1OF7rP8kY9CvX+OWfvPL9bGPFKbdXedqSZT27Lw1IQWdefxvGKeVXFZXksjKyQ8Wta0RL0rPZtYIInRteeNY=,iv:8xv8jVyPm59cPUxDBoEZ6PgUADofJoN9KT5uMWkIobU=,tag:qSp7b+tpR/cTapNIBgwtTQ==,type:str]",
    mac_only_encrypted: true,
    version: "3.13.2",
  },
}
