---
{
  apiVersion: "kustomize.toolkit.fluxcd.io/v1",
  kind: "Kustomization",
  metadata: {
    name: "kubevirt-plugin",
  },
  spec: {
    interval: "1h",
    path: "./kubernetes/apps/kubevirt/kubevirt-plugin/manifests",
    prune: false,
    sourceRef: {
      kind: "GitRepository",
      name: "flux-system",
      namespace: "flux-system",
    },
    dependsOn: [{
      name: "kubevirt-instance",
    }],
  },
}
