---
# yaml-language-server: $schema=https://kubernetes-schemas-9iu.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: flux-operator-web-config
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao
  target:
    name: flux-operator-web-config
    template:
      data:
        config.yaml: |
          apiVersion: web.fluxcd.controlplane.io/v1
          kind: Config
          spec:
            authentication:
              oauth2:
                autoLogin: true
                clientID: "{{ .OIDC_CLIENT_ID }}"
                clientSecret: "{{ .OIDC_CLIENT_SECRET }}"
                issuerURL: https://accounts.darkfellanetwork.com/realms/DarkfellaNET
                provider: OIDC
              type: OAuth2
            baseURL: https://flux-operator.darkfellanetwork.com
            userActions:
              access: Impersonated
  dataFrom:
    - extract:
        key: kv/flux-operator
