---
{
  apiVersion: "kustomize.config.k8s.io/v1beta1",
  kind: "Kustomization",
  resources: [
    # renovate: datasource=github-releases depName=kubevirt/kubevirt
    "https://github.com/kubevirt/kubevirt/releases/download/v1.8.2/kubevirt-operator.yaml",
  ],
  patches: [{
    target: {
      kind: "Namespace",
      name: "kubevirt",
    },
    patch: "[{\"op\": \"replace\", \"path\": \"/metadata/name\", \"value\": \"kubevirt-hyperconverged\"}]",
  }, {
    target: {
      kind: "Deployment",
      namespace: "kubevirt",
    },
    patch: "[{\"op\": \"replace\", \"path\": \"/metadata/namespace\", \"value\": \"kubevirt-hyperconverged\"}]",
  }, {
    target: {
      kind: "Service",
      namespace: "kubevirt",
    },
    patch: "[{\"op\": \"replace\", \"path\": \"/metadata/namespace\", \"value\": \"kubevirt-hyperconverged\"}]",
  }, {
    target: {
      kind: "ServiceAccount",
      namespace: "kubevirt",
    },
    patch: "[{\"op\": \"replace\", \"path\": \"/metadata/namespace\", \"value\": \"kubevirt-hyperconverged\"}]",
  }, {
    target: {
      kind: "ConfigMap",
      namespace: "kubevirt",
    },
    patch: "[{\"op\": \"replace\", \"path\": \"/metadata/namespace\", \"value\": \"kubevirt-hyperconverged\"}]",
  }, {
    target: {
      kind: "ClusterRoleBinding",
    },
    patch: "[{\"op\": \"replace\", \"path\": \"/subjects/0/namespace\", \"value\": \"kubevirt-hyperconverged\"}]",
  }, {
    target: {
      kind: "RoleBinding",
      namespace: "kubevirt",
    },
    patch: "[{\"op\": \"replace\", \"path\": \"/metadata/namespace\", \"value\": \"kubevirt-hyperconverged\"}, {\"op\": \"replace\", \"path\": \"/subjects/0/namespace\", \"value\": \"kubevirt-hyperconverged\"}]",
  }, {
    target: {
      kind: "Role",
      namespace: "kubevirt",
    },
    patch: "[{\"op\": \"replace\", \"path\": \"/metadata/namespace\", \"value\": \"kubevirt-hyperconverged\"}]",
  }],
}
