---
# yaml-language-server: $schema=https://51f35e2d.kubernetes-schemas-9iu.pages.dev/kubevirt.io/virtualmachine_v1alpha3.json
{
  apiVersion: "kubevirt.io/v1",
  kind: "VirtualMachine",
  metadata: {
    name: "nas-test",
    namespace: "virtualization",
  },
  spec: {
    runStrategy: "Always",
    template: {
      metadata: {
        labels: {
          kubevirt.io/domain: "nas-test",
        },
      },
      spec: {
        priorityClassName: "system-node-critical",
        networks: [{
          name: "bridge",
          multus: {
            default: true,
            networkName: "virtualization/nas",
          },
        }],
        domain: {
          clock: {
            utc: {},
          },
          cpu: {
            model: "host-passthrough",
            dedicatedCpuPlacement: true,
            isolateEmulatorThread: true,
            cores: 4,
          },
          ioThreadsPolicy: "auto",
          features: {
            acpi: {},
            apic: {},
            smm: {
              enabled: false,
            },
          },
          firmware: {
            bootloader: {
              efi: {
                secureBoot: false,
              },
            },
          },
          devices: {
            clientPassthrough: {},
            autoattachVSOCK: true,
            autoattachInputDevice: false,
            autoattachMemBalloon: false,
            filesystems: [{
              name: "tls-secret-fs",
              virtiofs: {},
            }],
            interfaces: [{
              name: "bridge",
              bridge: {},
              model: "virtio",
            }],
            disks: [{
              name: "os-disk",
              bootOrder: 1,
              disk: {
                bus: "virtio",
              },
            }, {
              name: "cloudinit",
              disk: {
                bus: "virtio",
              },
            }],
          },
          machine: {
            type: "q35",
          },
          resources: {
            requests: {
              cpu: 4,
              memory: "4Gi",
            },
            limits: {
              cpu: 4,
              memory: "4Gi",
            },
          },
        },
        volumes: [{
          name: "os-disk",
          dataVolume: {
            name: "nas-os-disk",
          },
        }, {
          name: "tls-secret-fs",
          secret: {
            secretName: "nas-tls",
          },
        }, {
          name: "cloudinit",
          cloudInitNoCloud: {
            userDataSecretRef: {
              name: "nas-cloudinit",
            },
          },
        }],
      },
    },
    dataVolumeTemplates: [{
      metadata: {
        name: "nas-os-disk",
      },
      spec: {
        storage: {
          storageClassName: "openebs-zfs-block-16k",
          accessModes: [
            "ReadWriteOnce",
          ],
          resources: {
            requests: {
              storage: "20Gi",
            },
          },
        },
        source: {
          http: {
            url: "https://cloud-images.ubuntu.com/noble/current/noble-server-cloudimg-amd64.img",
          },
        },
      },
    }],
  },
}
