---
# yaml-language-server: $schema=https://51f35e2d.kubernetes-schemas-9iu.pages.dev/external-secrets.io/externalsecret_v1beta1.json
{
  apiVersion: "external-secrets.io/v1",
  kind: "ExternalSecret",
  metadata: {
    name: "qui",
  },
  spec: {
    secretStoreRef: {
      kind: "ClusterSecretStore",
      name: "hashicorp-vault",
    },
    target: {
      name: "qui-secret",
      template: {
        data: {
          QUI__SESSION_SECRET: "{{ .QUI_SESSION_SECRET }}",
          QUI__OIDC_CLIENT_SECRET: "{{ .QUI_OIDC_CLIENT_SECRET }}",
          QUI__DATABASE_DSN: "postgresql://{{ .QUI_DATABASE_USER }}:{{ .QUI_DATABASE_PASSWORD | urlquery }}@postgres-db-rw.database.svc.cluster.local:5432/qui?sslmode=verify-full&sslrootcert=/etc/ssl/certs/postgres-ca.crt",
          ca.crt: "{{ index . \"ca.crt\" }}",
        },
      },
    },
    dataFrom: [{
      extract: {
        key: "secrets/qui",
      },
    }, {
      extract: {
        key: "secrets/certificates/postgres",
      },
    }],
  },
}
