---
# yaml-language-server: $schema=https://kubernetes-schemas-9iu.pages.dev/external-secrets.io/externalsecret_v1beta1.json
{
  apiVersion: "external-secrets.io/v1",
  kind: "ExternalSecret",
  metadata: {
    name: "postgres-admin",
  },
  spec: {
    secretStoreRef: {
      kind: "ClusterSecretStore",
      name: "openbao",
    },
    target: {
      name: "postgres-admin-secret",
      template: {
        engineVersion: "v2",
        metadata: {
          labels: {
            cnpg.io/reload: "true",
          },
        },
      },
    },
    dataFrom: [{
      extract: {
        key: "kv/postgres-admin",
      },
    }],
  },
}
---
# yaml-language-server: $schema=https://kubernetes-schemas-9iu.pages.dev/external-secrets.io/externalsecret_v1beta1.json
{
  apiVersion: "external-secrets.io/v1",
  kind: "ExternalSecret",
  metadata: {
    name: "keycloak-db-password",
  },
  spec: {
    secretStoreRef: {
      kind: "ClusterSecretStore",
      name: "openbao",
    },
    target: {
      name: "keycloak-db-password",
      template: {
        engineVersion: "v2",
        metadata: {
          labels: {
            cnpg.io/reload: "true",
          },
        },
        type: "kubernetes.io/basic-auth",
        data: {
          username: "{{ .username }}",
          password: "{{ .password }}",
        },
      },
    },
    data: [{
      secretKey: "username",
      remoteRef: {
        key: "kv/keycloak",
        property: "POSTGRES_USERNAME",
      },
    }, {
      secretKey: "password",
      remoteRef: {
        key: "kv/keycloak",
        property: "POSTGRES_PASSWORD",
      },
    }],
  },
}
---
# yaml-language-server: $schema=https://kubernetes-schemas-9iu.pages.dev/external-secrets.io/externalsecret_v1beta1.json
{
  apiVersion: "external-secrets.io/v1",
  kind: "ExternalSecret",
  metadata: {
    name: "bazarr-db-password",
  },
  spec: {
    secretStoreRef: {
      kind: "ClusterSecretStore",
      name: "openbao",
    },
    target: {
      name: "bazarr-db-password",
      template: {
        engineVersion: "v2",
        metadata: {
          labels: {
            cnpg.io/reload: "true",
          },
        },
        type: "kubernetes.io/basic-auth",
        data: {
          username: "{{ .username }}",
          password: "{{ .password }}",
        },
      },
    },
    data: [{
      secretKey: "username",
      remoteRef: {
        key: "kv/bazarr",
        property: "POSTGRES_USERNAME",
      },
    }, {
      secretKey: "password",
      remoteRef: {
        key: "kv/bazarr",
        property: "POSTGRES_PASSWORD",
      },
    }],
  },
}
---
# yaml-language-server: $schema=https://kubernetes-schemas-9iu.pages.dev/external-secrets.io/externalsecret_v1beta1.json
{
  apiVersion: "external-secrets.io/v1",
  kind: "ExternalSecret",
  metadata: {
    name: "radarr-db-password",
  },
  spec: {
    secretStoreRef: {
      kind: "ClusterSecretStore",
      name: "openbao",
    },
    target: {
      name: "radarr-db-password",
      template: {
        engineVersion: "v2",
        metadata: {
          labels: {
            cnpg.io/reload: "true",
          },
        },
        type: "kubernetes.io/basic-auth",
        data: {
          username: "{{ .username }}",
          password: "{{ .password }}",
        },
      },
    },
    data: [{
      secretKey: "username",
      remoteRef: {
        key: "kv/radarr",
        property: "POSTGRES_USERNAME",
      },
    }, {
      secretKey: "password",
      remoteRef: {
        key: "kv/radarr",
        property: "POSTGRES_PASSWORD",
      },
    }],
  },
}
---
# yaml-language-server: $schema=https://kubernetes-schemas-9iu.pages.dev/external-secrets.io/externalsecret_v1beta1.json
{
  apiVersion: "external-secrets.io/v1",
  kind: "ExternalSecret",
  metadata: {
    name: "sonarr-db-password",
  },
  spec: {
    secretStoreRef: {
      kind: "ClusterSecretStore",
      name: "openbao",
    },
    target: {
      name: "sonarr-db-password",
      template: {
        engineVersion: "v2",
        metadata: {
          labels: {
            cnpg.io/reload: "true",
          },
        },
        type: "kubernetes.io/basic-auth",
        data: {
          username: "{{ .username }}",
          password: "{{ .password }}",
        },
      },
    },
    data: [{
      secretKey: "username",
      remoteRef: {
        key: "kv/sonarr",
        property: "POSTGRES_USERNAME",
      },
    }, {
      secretKey: "password",
      remoteRef: {
        key: "kv/sonarr",
        property: "POSTGRES_PASSWORD",
      },
    }],
  },
}
---
# yaml-language-server: $schema=https://kubernetes-schemas-9iu.pages.dev/external-secrets.io/externalsecret_v1beta1.json
{
  apiVersion: "external-secrets.io/v1",
  kind: "ExternalSecret",
  metadata: {
    name: "prowlarr-db-password",
  },
  spec: {
    secretStoreRef: {
      kind: "ClusterSecretStore",
      name: "openbao",
    },
    target: {
      name: "prowlarr-db-password",
      template: {
        engineVersion: "v2",
        metadata: {
          labels: {
            cnpg.io/reload: "true",
          },
        },
        type: "kubernetes.io/basic-auth",
        data: {
          username: "{{ .username }}",
          password: "{{ .password }}",
        },
      },
    },
    data: [{
      secretKey: "username",
      remoteRef: {
        key: "kv/prowlarr",
        property: "POSTGRES_USERNAME",
      },
    }, {
      secretKey: "password",
      remoteRef: {
        key: "kv/prowlarr",
        property: "POSTGRES_PASSWORD",
      },
    }],
  },
}
---
# yaml-language-server: $schema=https://kubernetes-schemas-9iu.pages.dev/external-secrets.io/externalsecret_v1beta1.json
{
  apiVersion: "external-secrets.io/v1",
  kind: "ExternalSecret",
  metadata: {
    name: "autobrr-db-password",
  },
  spec: {
    secretStoreRef: {
      kind: "ClusterSecretStore",
      name: "openbao",
    },
    target: {
      name: "autobrr-db-password",
      template: {
        engineVersion: "v2",
        metadata: {
          labels: {
            cnpg.io/reload: "true",
          },
        },
        type: "kubernetes.io/basic-auth",
        data: {
          username: "{{ .username }}",
          password: "{{ .password }}",
        },
      },
    },
    data: [{
      secretKey: "username",
      remoteRef: {
        key: "kv/autobrr",
        property: "POSTGRES_USERNAME",
      },
    }, {
      secretKey: "password",
      remoteRef: {
        key: "kv/autobrr",
        property: "POSTGRES_PASSWORD",
      },
    }],
  },
}
---
# yaml-language-server: $schema=https://kubernetes-schemas-9iu.pages.dev/external-secrets.io/externalsecret_v1beta1.json
{
  apiVersion: "external-secrets.io/v1",
  kind: "ExternalSecret",
  metadata: {
    name: "seerr-db-password",
  },
  spec: {
    secretStoreRef: {
      kind: "ClusterSecretStore",
      name: "openbao",
    },
    target: {
      name: "seerr-db-password",
      template: {
        engineVersion: "v2",
        metadata: {
          labels: {
            cnpg.io/reload: "true",
          },
        },
        type: "kubernetes.io/basic-auth",
        data: {
          username: "{{ .DB_USER }}",
          password: "{{ .DB_PASS }}",
        },
      },
    },
    dataFrom: [{
      extract: {
        key: "kv/seerr",
      },
    }],
  },
}
---
# yaml-language-server: $schema=https://kubernetes-schemas-9iu.pages.dev/external-secrets.io/externalsecret_v1beta1.json
{
  apiVersion: "external-secrets.io/v1",
  kind: "ExternalSecret",
  metadata: {
    name: "vaultwarden-db-password",
  },
  spec: {
    secretStoreRef: {
      kind: "ClusterSecretStore",
      name: "openbao",
    },
    target: {
      name: "vaultwarden-db-password",
      template: {
        engineVersion: "v2",
        metadata: {
          labels: {
            cnpg.io/reload: "true",
          },
        },
        type: "kubernetes.io/basic-auth",
        data: {
          username: "{{ .username }}",
          password: "{{ .password }}",
        },
      },
    },
    data: [{
      secretKey: "username",
      remoteRef: {
        key: "kv/vaultwarden",
        property: "POSTGRES_USERNAME",
      },
    }, {
      secretKey: "password",
      remoteRef: {
        key: "kv/vaultwarden",
        property: "POSTGRES_PASSWORD",
      },
    }],
  },
}
---
# yaml-language-server: $schema=https://kubernetes-schemas-9iu.pages.dev/external-secrets.io/externalsecret_v1beta1.json
{
  apiVersion: "external-secrets.io/v1",
  kind: "ExternalSecret",
  metadata: {
    name: "artifactory-db-password",
  },
  spec: {
    secretStoreRef: {
      kind: "ClusterSecretStore",
      name: "openbao",
    },
    target: {
      name: "artifactory-db-password",
      template: {
        engineVersion: "v2",
        metadata: {
          labels: {
            cnpg.io/reload: "true",
          },
        },
        type: "kubernetes.io/basic-auth",
        data: {
          username: "{{ .username }}",
          password: "{{ .password }}",
        },
      },
    },
    data: [{
      secretKey: "username",
      remoteRef: {
        key: "kv/artifactory",
        property: "db-user",
      },
    }, {
      secretKey: "password",
      remoteRef: {
        key: "kv/artifactory",
        property: "db-password",
      },
    }],
  },
}
---
# yaml-language-server: $schema=https://kubernetes-schemas-9iu.pages.dev/external-secrets.io/externalsecret_v1beta1.json
{
  apiVersion: "external-secrets.io/v1",
  kind: "ExternalSecret",
  metadata: {
    name: "gatus-db-password",
  },
  spec: {
    secretStoreRef: {
      kind: "ClusterSecretStore",
      name: "openbao",
    },
    target: {
      name: "gatus-db-password",
      template: {
        engineVersion: "v2",
        metadata: {
          labels: {
            cnpg.io/reload: "true",
          },
        },
        type: "kubernetes.io/basic-auth",
        data: {
          username: "{{ .username }}",
          password: "{{ .password }}",
        },
      },
    },
    data: [{
      secretKey: "username",
      remoteRef: {
        key: "kv/gatus",
        property: "POSTGRES_USERNAME",
      },
    }, {
      secretKey: "password",
      remoteRef: {
        key: "kv/gatus",
        property: "POSTGRES_PASSWORD",
      },
    }],
  },
}
---
# yaml-language-server: $schema=https://kubernetes-schemas-9iu.pages.dev/external-secrets.io/externalsecret_v1beta1.json
{
  apiVersion: "external-secrets.io/v1",
  kind: "ExternalSecret",
  metadata: {
    name: "qui-db-password",
  },
  spec: {
    secretStoreRef: {
      kind: "ClusterSecretStore",
      name: "openbao",
    },
    target: {
      name: "qui-db-password",
      template: {
        engineVersion: "v2",
        metadata: {
          labels: {
            cnpg.io/reload: "true",
          },
        },
        type: "kubernetes.io/basic-auth",
        data: {
          username: "{{ .username }}",
          password: "{{ .password }}",
        },
      },
    },
    data: [{
      secretKey: "username",
      remoteRef: {
        key: "kv/qui",
        property: "QUI_DATABASE_USER",
      },
    }, {
      secretKey: "password",
      remoteRef: {
        key: "kv/qui",
        property: "QUI_DATABASE_PASSWORD",
      },
    }],
  },
}
