---
# yaml-language-server: $schema=https://51f35e2d.kubernetes-schemas-9iu.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
{
  apiVersion: "helm.toolkit.fluxcd.io/v2",
  kind: "HelmRelease",
  metadata: {
    name: "flux-instance",
  },
  spec: {
    interval: "1h",
    chartRef: {
      kind: "OCIRepository",
      name: "flux-instance",
    },
    values: {
      instance: {
        distribution: {
          artifact: "oci://ghcr.io/controlplaneio-fluxcd/flux-operator-manifests:v0.46.0",
        },
        cluster: {
          networkPolicy: false,
        },
        storage: {
          class: "openebs-zfs-128k",
          size: "20Gi",
        },
        components: [
          "source-controller",
          "kustomize-controller",
          "helm-controller",
          "notification-controller",
        ],
        sync: {
          kind: "GitRepository",
          url: "https://github.com/d4rkfella/home-ops",
          ref: "refs/heads/main",
          path: "kubernetes/flux/cluster",
          interval: "1h",
          recurseSubmodules: true,
        },
        kustomize: {
          patches: [
            # Increase the number of workers and limits
            # Ref: https://fluxcd.io/flux/installation/configuration/vertical-scaling/#increase-the-number-of-workers-and-limits
            {
              patch: "\
                 - op: add\n\
                \  path: /spec/template/spec/containers/0/args/-\n\
                \  value: --concurrent=10\n\
                 - op: add\n\
                \  path: /spec/template/spec/containers/0/args/-\n\
                \  value: --requeue-dependency=5s\n\
                ",
              target: {
                kind: "Deployment",
                name: "(kustomize-controller|helm-controller|source-controller)",
              },
            },
            {
              patch: "\
                 apiVersion: apps/v1\n\
                 kind: Deployment\n\
                 metadata:\n\
                \  name: all\n\
                 spec:\n\
                \  template:\n\
                \    spec:\n\
                \      containers:\n\
                \        - name: manager\n\
                \          resources:\n\
                \            limits:\n\
                \              memory: 2Gi\n\
                ",
              target: {
                kind: "Deployment",
                name: "(kustomize-controller|helm-controller|source-controller)",
              },
            },
            # Enable in-memory kustomize builds
            # Ref: https://fluxcd.io/flux/installation/configuration/vertical-scaling/#enable-in-memory-kustomize-builds
            {
              patch: "\
                 - op: add\n\
                \  path: /spec/template/spec/containers/0/args/-\n\
                \  value: --concurrent=20\n\
                 - op: replace\n\
                \  path: /spec/template/spec/volumes/0\n\
                \  value:\n\
                \    name: temp\n\
                \    emptyDir:\n\
                \      medium: Memory\n\
                ",
              target: {
                kind: "Deployment",
                name: "kustomize-controller",
              },
            },
            # Enable Helm repositories caching
            # Ref: https://fluxcd.io/flux/installation/configuration/vertical-scaling/#enable-helm-repositories-caching
            {
              patch: "\
                 - op: add\n\
                \  path: /spec/template/spec/containers/0/args/-\n\
                \  value: --helm-cache-max-size=30\n\
                 - op: add\n\
                \  path: /spec/template/spec/containers/0/args/-\n\
                \  value: --helm-cache-ttl=60m\n\
                 - op: add\n\
                \  path: /spec/template/spec/containers/0/args/-\n\
                \  value: --helm-cache-purge-interval=5m\n\
                ",
              target: {
                kind: "Deployment",
                name: "source-controller",
              },
            },
            # Flux near OOM detection for Helm
            # Ref: https://fluxcd.io/flux/installation/configuration/helm-oom-detection/
            {
              patch: "\
                 - op: add\n\
                \  path: /spec/template/spec/containers/0/args/-\n\
                \  value: --feature-gates=OOMWatch=true\n\
                 - op: add\n\
                \  path: /spec/template/spec/containers/0/args/-\n\
                \  value: --oom-watch-memory-threshold=95\n\
                 - op: add\n\
                \  path: /spec/template/spec/containers/0/args/-\n\
                \  value: --oom-watch-interval=500ms\n\
                ",
              target: {
                kind: "Deployment",
                name: "helm-controller",
              },
            },
            {
              patch: "\
                 - op: add\n\
                \  path: /spec/template/spec/hostUsers\n\
                \  value: false\n\
                ",
              target: {
                kind: "Deployment",
                name: "(kustomize-controller|helm-controller|source-controller|notification-controller)",
              },
            },
            {
              # Default to retry on failure
              patch: "\
                 - op: add\n\
                \  path: /spec/template/spec/containers/0/args/-\n\
                \  value: --feature-gates=DefaultToRetryOnFailure=true\
                ",
              target: {
                kind: "Deployment",
                name: "helm-controller",
              },
            },
            {
              # Controller-level SOPS decryption
              patch: "\
                 - op: add\n\
                \  path: /spec/template/spec/containers/0/args/-\n\
                \  value: --sops-age-secret=sops-age-secret\
                ",
              target: {
                kind: "Deployment",
                name: "kustomize-controller",
              },
            },
            {
              # Watch configmaps and secrets attached to HelmReleases and Kustomizations
              patch: "\
                 - op: add\n\
                \  path: /spec/template/spec/containers/0/args/-\n\
                \  value: --watch-configs-label-selector=owner!=helm\
                ",
              target: {
                kind: "Deployment",
                name: "(helm-controller|kustomize-controller)",
              },
            },
            {
              patch: "\
                 - op: add\n\
                \  path: /spec/template/spec/containers/0/args/-\n\
                \  value: --log-level=debug\n\
                ",
              target: {
                kind: "Deployment",
                name: "helm-controller",
              },
            },
          ],
        },
      },
    },
  },
}
