---
# yaml-language-server: $schema=https://kubernetes-schemas-9iu.pages.dev/tuppr.home-operations.com/talosupgrade_v1alpha1.json
{
  apiVersion: "tuppr.home-operations.com/v1alpha1",
  kind: "TalosUpgrade",
  metadata: {
    name: "talos",
  },
  spec: {
    talos: {
      # renovate: datasource=custom.talos-factory depName=siderolabs/talos
      version: "v1.13.7",
    },
    policy: {
      rebootMode: "default",
    },
    healthChecks: [{
      apiVersion: "volsync.backube/v1alpha1",
      kind: "ReplicationSource",
      expr: "status.conditions.filter(c, c.type == \"Synchronizing\").all(c, c.status == \"False\")",
    }],
    hooks: {
      pre: [{
        name: "nas-nfs-quiesce",
        image: "alpine/k8s:1.36.2@sha256:44ef4942e171939b9c665a4a84beb80e2dcdb9a24330d4651cfdfd2e9deecc47",
        serviceAccountName: "tuppr-nfs-hook",
        command: [
          "/bin/bash",
          "/scripts/pre.sh",
        ],
        securityContext: {
          runAsNonRoot: true,
          runAsUser: 65532,
          runAsGroup: 65532,
          allowPrivilegeEscalation: false,
          readOnlyRootFilesystem: true,
          capabilities: {
            drop: [
              "ALL",
            ],
          },
          seccompProfile: {
            type: "RuntimeDefault",
          },
        },
        volumeMounts: [{
          name: "hook-scripts",
          mountPath: "/scripts",
        }, {
          name: "tmp",
          mountPath: "/tmp",
        }],
        volumes: [{
          name: "hook-scripts",
          configMap: {
            name: "nfs-quiesce-scripts",
            defaultMode: 493,
          },
        }, {
          name: "tmp",
          emptyDir: {},
        }],
      }],
      post: [{
        name: "restore-nfs-consumers",
        image: "alpine/k8s:1.36.2@sha256:44ef4942e171939b9c665a4a84beb80e2dcdb9a24330d4651cfdfd2e9deecc47",
        serviceAccountName: "tuppr-nfs-hook",
        command: [
          "/bin/bash",
          "/scripts/post.sh",
        ],
        securityContext: {
          runAsNonRoot: true,
          runAsUser: 65532,
          runAsGroup: 65532,
          allowPrivilegeEscalation: false,
          readOnlyRootFilesystem: true,
          capabilities: {
            drop: [
              "ALL",
            ],
          },
          seccompProfile: {
            type: "RuntimeDefault",
          },
        },
        volumeMounts: [{
          name: "hook-scripts",
          mountPath: "/scripts",
        }, {
          name: "tmp",
          mountPath: "/tmp",
        }],
        volumes: [{
          name: "hook-scripts",
          configMap: {
            name: "nfs-quiesce-scripts",
            defaultMode: 493,
          },
        }, {
          name: "tmp",
          emptyDir: {},
        }],
      }],
    },
  },
}
