---
{
  apiVersion: "kustomize.config.k8s.io/v1beta1",
  kind: "Kustomization",
  resources: [
    "./serviceaccount.yaml",
    "./user-cluster-admin.yaml",
    "./rbac.yaml",
    "./deployment.yaml",
    "./service.yaml",
    "./kubevirt-consoleplugin.yaml",
    "./httproute.yaml",
    "./externalsecret.yaml",
  ],
}
