---
{
  apiVersion: "apps/v1",
  kind: "Deployment",
  metadata: {
    name: "kubevirt-plugin",
    labels: {
      app: "kubevirt-plugin",
    },
  },
  spec: {
    replicas: 1,
    selector: {
      matchLabels: {
        app: "kubevirt-plugin",
      },
    },
    template: {
      metadata: {
        labels: {
          app: "kubevirt-plugin",
        },
      },
      spec: {
        initContainers: [{
          name: "setup",
          image: "quay.io/kubevirt-ui/kubevirt-plugin:latest",
          command: [
            "sh",
            "-c",
          ],
          args: [
            "cp -r /opt/app-root/etc/* /tmp/app-root-etc/ && cp -r /var/lib/nginx/* /tmp/nginx-lib/",
          ],
          volumeMounts: [{
            name: "app-root-etc",
            mountPath: "/tmp/app-root-etc",
          }, {
            name: "nginx-lib",
            mountPath: "/tmp/nginx-lib",
          }],
          securityContext: {
            allowPrivilegeEscalation: false,
            readOnlyRootFilesystem: true,
            runAsNonRoot: true,
            runAsUser: 1000,
          },
        }],
        containers: [{
          name: "plugin",
          image: "quay.io/kubevirt-ui/kubevirt-plugin:latest",
          ports: [{
            name: "http",
            containerPort: 80,
            protocol: "TCP",
          }],
          resources: {
            requests: {
              cpu: "50m",
              memory: "128Mi",
            },
            limits: {
              cpu: "200m",
              memory: "256Mi",
            },
          },
          securityContext: {
            allowPrivilegeEscalation: false,
            readOnlyRootFilesystem: true,
            runAsNonRoot: true,
            runAsUser: 1000,
            capabilities: {
              drop: [
                "ALL",
              ],
            },
          },
          volumeMounts: [{
            name: "app-root-etc",
            mountPath: "/opt/app-root/etc",
          }, {
            name: "nginx-logs",
            mountPath: "/var/log/nginx",
          }, {
            name: "nginx-cache",
            mountPath: "/var/cache/nginx",
          }, {
            name: "nginx-run",
            mountPath: "/var/run",
          }, {
            name: "nginx-lib",
            mountPath: "/var/lib/nginx",
          }, {
            name: "serving-cert",
            mountPath: "/var/serving-cert",
          }],
        }],
        volumes: [{
          name: "app-root-etc",
          emptyDir: {},
        }, {
          name: "nginx-logs",
          emptyDir: {},
        }, {
          name: "nginx-cache",
          emptyDir: {},
        }, {
          name: "nginx-run",
          emptyDir: {},
        }, {
          name: "nginx-lib",
          emptyDir: {},
        }, {
          name: "serving-cert",
          secret: {
            secretName: "kubevirt-plugin-serving-cert",
          },
        }],
      },
    },
  },
}
