---
# yaml-language-server: $schema=https://51f35e2d.kubernetes-schemas-9iu.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
{
  apiVersion: "helm.toolkit.fluxcd.io/v2",
  kind: "HelmRelease",
  metadata: {
    name: "kubevirt-plugin",
  },
  spec: {
    interval: "1h",
    chartRef: {
      kind: "OCIRepository",
      name: "kubevirt-plugin",
    },
    values: {
      controllers: {
        kubevirt-plugin: {
          annotations: {
            reloader.stakater.com/auto: "true",
          },
          containers: {
            app: {
              image: {
                repository: "ghcr.io/d4rkfella/kubevirt-plugin",
                tag: "dev@sha256:8b6bea6452ccdd744c68a4aa5c844221ae66087a63987197dbdf904e467a0cd1",
              },
              securityContext: {
                allowPrivilegeEscalation: false,
                readOnlyRootFilesystem: true,
                capabilities: {
                  drop: [
                    "ALL",
                  ],
                },
              },
              resources: {
                requests: {
                  cpu: "100m",
                  memory: "128Mi",
                },
                limits: {
                  cpu: "500m",
                  memory: "512Mi",
                },
              },
            },
          },
        },
      },
      defaultPodOptions: {
        securityContext: {
          runAsNonRoot: true,
          runAsUser: 101,
          runAsGroup: 101,
          fsGroup: 101,
          fsGroupChangePolicy: "OnRootMismatch",
          seccompProfile: {
            type: "RuntimeDefault",
          },
        },
      },
      service: {
        app: {
          controller: "kubevirt-plugin",
          ports: {
            http: {
              port: 9443,
            },
          },
        },
      },
      persistence: {
        cert: {
          type: "secret",
          name: "kubevirt-plugin-serving-cert",
          globalMounts: [{
            path: "/var/serving-cert",
          }],
        },
        logs: {
          type: "emptyDir",
          globalMounts: [{
            path: "/var/log/nginx",
          }],
        },
        cache: {
          type: "emptyDir",
          globalMounts: [{
            path: "/var/cache/nginx",
          }],
        },
        run: {
          type: "emptyDir",
          globalMounts: [{
            path: "/var/run",
          }],
        },
        tmp: {
          type: "emptyDir",
          globalMounts: [{
            path: "/tmp",
          }],
        },
      },
    },
  },
}
