defaults
auth           on
tls            on
tls_trust_file /etc/ssl/certs/ca-certificates.crt
logfile        /var/log/msmtp.log

account        brevo
host           smtp-relay.brevo.com
port           587
from           nas@darkfellanetwork.com
user           {{ .SMTP_USERNAME }}
password       {{ .SMTP_API_TOKEN }}

account default : brevo
