---
{
  # yaml-language-server: $schema=https://51f35e2d.kubernetes-schemas-9iu.pages.dev/external-secrets.io/externalsecret_v1beta1.json
  apiVersion: "external-secrets.io/v1",
  kind: "ExternalSecret",
  metadata: {
    name: "nas-cloudinit",
  },
  spec: {
    secretStoreRef: {
      kind: "ClusterSecretStore",
      name: "hashicorp-vault",
    },
    target: {
      name: "nas-cloudinit",
      template: {
        data: {
          userdata: "\
             #cloud-config\n\
             hostname: nas\n\
             fqdn: nas.darkfellanetwork.com\n\
             timezone: Europe/Sofia\n\
             users:\n\
            \  - name: nas_admin\n\
            \    groups: [sudo, users, systemd-journal, adm]\n\
            \    sudo: ALL=(ALL) NOPASSWD:ALL\n\
            \    shell: /bin/bash\n\
            \    lock_passwd: false\n\
            \    passwd: {{ .NAS_ADMIN_PASSWORD }}\n\
             \n\
            \  - name: kubernetes_workloads\n\
            \    uid: 65532\n\
            \    shell: /usr/sbin/nologin\n\
            \    lock_passwd: true\n\
            \    no_create_home: true\n\
            \    sudo: null\n\
             \n\
            \  - name: artifactory-system\n\
            \    uid: 1030\n\
            \    shell: /usr/sbin/nologin\n\
            \    lock_passwd: true\n\
            \    no_create_home: true\n\
            \    sudo: null\n\
             \n\
             package_update: true\n\
             package_upgrade: true\n\
             \n\
             packages:\n\
            \  - nfs-kernel-server\n\
            \  - nfs-common\n\
            \  - zfsutils-linux\n\
            \  - acl\n\
            \  - attr\n\
            \  - samba\n\
             \n\
             write_files:\n\
            \  - path: /etc/nfs.conf.d/local.conf\n\
            \    content: |\n\
            \      [nfsd]\n\
            \      vers3=n\n\
            \      vers4=y\n\
            \      vers4.1=y\n\
            \      vers4.2=y\n\
             \n\
            \  - path: /etc/exports\n\
            \    content: |\n\
            \      /mnt/exos20/data *(sec=sys,rw,insecure,no_subtree_check)\n\
            \      /mnt/exos20/data/media *(sec=sys,rw,insecure,subtree_check)\n\
            \      /mnt/exos20/data/downloads/torrents *(sec=sys,rw,insecure,subtree_check)\n\
            \      /mnt/exos20/SMB/LaunchBox *(sec=sys,rw,insecure,subtree_check)\n\
            \      /mnt/exos20/artifactory-backup *(sec=sys,rw,insecure,no_subtree_check)\n\
             \n\
             runcmd:\n\
            \  - systemctl enable zfs-import-cache.service\n\
            \  - systemctl enable zfs-import.target\n\
            \  - systemctl enable zfs-mount.service\n\
            \  - systemctl enable zfs.target\n\
            \  - ufw allow 2049/tcp || true\n\
            \  - zpool import -f exos20 || true\n\
            \  - zfs set acltype=nfsv4 exos20/data || true\n\
            \  - zfs set aclinherit=passthrough exos20/data || true\n\
            \  - zfs set aclmode=passthrough exos20/data || true\n\
            \  - zfs set xattr=sa exos20/data || true\n\
            \  - exportfs -ra\n\
            \  - systemctl enable --now nfs-kernel-server\n\
            ",
        },
      },
    },
    dataFrom: [{
      extract: {
        key: "secrets/nas-admin",
      },
    }],
  },
}
