---
{
  apiVersion: "kustomize.config.k8s.io/v1beta1",
  kind: "Kustomization",
  resources: [
    "./networkattachmentdefinition.yaml",
    "./certificate.yaml",
    "./externalsecret.yaml",
    "./virtualmachine.yaml",
    "./scrapeconfig.yaml",
    "./grafanadashboard.yaml",
  ],
}
