---
{
  apiVersion: "v1",
  kind: "Secret",
  metadata: {
    name: "zerossl-credentials",
  },
  stringData: {
    EAB_HMAC_KEY: "ENC[AES256_GCM,data:2CId8Hly1PSt8xQwOF2Vya9SunkTGtSV+qYP6uhAxafju+rwMD1aoxzZ2TjleSAbY+Ehi0yopEw6+5ZO2xl2f8yBbIPxyaYQde8VjU3jgYUmsfpw95c=,iv:a4ru0QyuOr7/TL5hsSUGNbFUuqJ6b/R/NENSUSgvd1E=,tag:PAALYZreZDAEbtuW5edI8w==,type:str]",
    CF_API_TOKEN: "ENC[AES256_GCM,data:fJzP1qNFu1POx9qVRU+OuAuQUxISD2UipAUiwdElDzvuRnjIl7/iQC9ZFKuigF0jhvoEsR0=,iv:7rQjonAlm1j+Dld5CN9bY75x54FS2ZdBP7hMHKx7ZWc=,tag:Xomms1vhxSGqkoxoMCnatg==,type:str]",
  },
  sops: {
    age: [{
      recipient: "age1frhtpr8u3u99pvcuq5mjevxdq9agjfpkd8fjtnpj9qymzh5v845q53f37d",
      enc: "\
         -----BEGIN AGE ENCRYPTED FILE-----\n\
         YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPZ0xSTktlbXYxRUhLVktQ\n\
         L3JMNFp2SU1qVzdVMkdiL1Zoa1o0Q3V4RlZvCmpFb0hyL2pQb0RuKytxNHVHM1l4\n\
         SnE3VTd6dnI2QlpJaGZ6N0NkbURyMG8KLS0tIEwxVHV3U0FBZmJmUkF2MU9BbC9L\n\
         czZWYmhiNWlhQ1FIbzNwUHl3bThXMjgKoXCgBtmPF8GWNWkrKO+eQJDKTxsRT4qT\n\
         AlbSBEKg5fbQ3JCsvoxuMNer6uy47Ji//cKV6M/9WKMJaJATPpvQKw==\n\
         -----END AGE ENCRYPTED FILE-----\n\
        ",
    }],
    lastmodified: "2026-04-06T12:50:02Z",
    mac: "ENC[AES256_GCM,data:R3MD1nDQKo/P9Unh29Rudze0XBWIAvQzyw3ZSy/VfikOkBnZAKVh1TbWVWrv4Q+d8fDlPCfYgF8+c3G+DYX836sSOV7CyrcOHbSQIstfmDucU0i+lfY8I+lhRKXzVHJXHn5FT5A0eOuPDfTB83T4+ITKaVt2y7mBX68CwKoWdVQ=,iv:sLmrNmn2nu+2NQmSJJEPPlmwqODTx+MMPurxuQA0qaw=,tag:MsnzjaRtH8bbguHZAW9FvQ==,type:str]",
    encrypted_regex: "^(data|stringData)$",
    mac_only_encrypted: true,
    version: "3.12.2",
  },
}
