---
# yaml-language-server: $schema=https://51f35e2d.kubernetes-schemas-9iu.pages.dev/cert-manager.io/issuer_v1.json
{
  apiVersion: "cert-manager.io/v1",
  kind: "Issuer",
  metadata: {
    name: "selfsigned-root-ca",
  },
  spec: {
    selfSigned: {},
  },
}
---
# yaml-language-server: $schema=https://51f35e2d.kubernetes-schemas-9iu.pages.dev/cert-manager.io/certificate_v1.json
{
  apiVersion: "cert-manager.io/v1",
  kind: "Certificate",
  metadata: {
    name: "artifactory-ca",
  },
  spec: {
    isCA: true,
    commonName: "Artifactory-Root-CA",
    secretName: "artifactory-ca",
    duration: "87600h",
    renewBefore: "720h",
    issuerRef: {
      name: "selfsigned-root-ca",
      kind: "Issuer",
    },
    privateKey: {
      algorithm: "RSA",
      encoding: "PKCS1",
      size: 2048,
    },
  },
}
