---
# yaml-language-server: $schema=https://51f35e2d.kubernetes-schemas-9iu.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
{
  apiVersion: "helm.toolkit.fluxcd.io/v2",
  kind: "HelmRelease",
  metadata: {
    name: "artifactory",
  },
  spec: {
    interval: "1h",
    chartRef: {
      kind: "OCIRepository",
      name: "artifactory",
    },
    postRenderers: [{
      kustomize: {
        patches: [{
          target: {
            kind: "StatefulSet",
            name: "artifactory",
          },
          patch: "\
             - op: add\n\
            \  path: /spec/template/spec/imagePullSecrets\n\
            \  value:\n\
            \    - name: artifactory-secret\
            ",
        }],
      },
    }],
    values: {
      mc: {
        enabled: true,
      },
      access: {
        accessConfig: {
          security: {
            tls: true,
          },
        },
        customCertificatesSecretName: "artifactory-ca",
      },
      jfconnect: {
        enabled: true,
      },
      onemodel: {
        enabled: true,
      },
      artifactory: {
        statefulset: {
          annotations: {
            reloader.stakater.com/auto: "true",
          },
        },
        license: {
          secret: "artifactory-secret",
          dataKey: "license-key",
        },
        image: {
          registry: "ghcr.io",
          repository: "d4rkfella/artifactory-pro",
          tag: "7.133.15@sha256:daa5b9099300a35b0e778065fd8c5ca3a9be02f43923923796b8b6fbf1314193",
          pullPolicy: "IfNotPresent",
        },
        persistence: {
          size: "200Gi",
        },
        customVolumes: "\
           - name: nfs-backup-volume\n\
          \  nfs:\n\
          \    server: 192.168.91.40\n\
          \    path: /mnt/exos20/artifactory-backup\n\
          ",
        customVolumeMounts: "\
           - name: nfs-backup-volume\n\
          \  mountPath: /var/opt/jfrog/artifactory/backup/nfs\n\
          ",
        haBackupDir: {
          enabled: true,
          path: "/var/opt/jfrog/artifactory/backup/nfs",
        },
        extraSystemYaml: {
          artifactory: {
            tomcat: {
              httpsConnector: {
                enabled: true,
              },
            },
            backup: {
              dir: "/var/opt/jfrog/artifactory/backup/nfs",
            },
          },
        },
        masterKeySecretName: "artifactory-secret",
        joinKeySecretName: "artifactory-secret",
        admin: {
          secret: "artifactory-secret",
          dataKey: "bootstrap.creds",
        },
      },
      postgresql: {
        enabled: false,
      },
      database: {
        type: "postgresql",
        driver: "org.postgresql.Driver",
        secrets: {
          user: {
            name: "artifactory-secret",
            key: "db-user",
          },
          password: {
            name: "artifactory-secret",
            key: "db-password",
          },
          url: {
            name: "artifactory-secret",
            key: "db-url",
          },
        },
      },
      nginx: {
        enabled: false,
      },
    },
  },
}
