---
# yaml-language-server: $schema=https://51f35e2d.kubernetes-schemas-9iu.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
{
  apiVersion: "helm.toolkit.fluxcd.io/v2",
  kind: "HelmRelease",
  metadata: {
    name: "artifactory",
  },
  spec: {
    interval: "1h",
    chartRef: {
      kind: "OCIRepository",
      name: "artifactory",
    },
    values: {
      global: {
        jfrog: {
          observability: {
            branch: "master",
          },
        },
        prometheus: {
          loki_url: "http://loki-headless.observability.svc.cluster.local:3100",
          release_name: "prometheus",
        },
      },
      mc: {
        enabled: false,
      },
      access: {
        javaOpts: {
          other: "-XX:InitialRAMPercentage=20 -XX:MaxRAMPercentage=70 -javaagent:/opt/jfrog/access/app/access/jfrog-access-license-patcher-1.0.jar",
        },
        accessConfig: {
          security: {
            tls: true,
          },
        },
        customCertificatesSecretName: "artifactory-ca",
      },
      jfconnect: {
        enabled: false,
      },
      onemodel: {
        enabled: true,
      },
      artifactory: {
        statefulset: {
          annotations: {
            reloader.stakater.com/auto: "true",
          },
        },
        openMetrics: {
          enabled: true,
        },
        tags: {
          disableAnalytics: true,
        },
        customSidecarContainers: "\
           - name: \"artifactory-fluentd-sidecar\"\n\
          \  image: \"ghcr.io/d4rkfella/fluent-plugin-prometheus:2.2.1@sha256:446101b5be1b36b7c35efa49b2bab9a3fa600f94de0ac7e04ae0a5381e698572\"\n\
          \  imagePullPolicy: \"IfNotPresent\"\n\
          \  command:\n\
          \    - sh\n\
          \    - '-c'\n\
          \  args:\n\
          \    - >\n\
          \      curl https://raw.githubusercontent.com/jfrog/log-analytics-prometheus/{{ .Values.global.jfrog.observability.branch }}/fluent_metrics.conf.rt -o /tmp/fluentd_metrics.conf;\n\
          \      fluentd -v -c /tmp/fluentd_metrics.conf\n\
          \  volumeMounts:\n\
          \    - mountPath: \"{{ .Values.artifactory.persistence.mountPath }}\"\n\
          \      name: artifactory-volume\n\
          \  env:\n\
          \    - name: JF_PRODUCT_DATA_INTERNAL\n\
          \      value: {{ .Values.artifactory.persistence.mountPath }}\n\
          \    - name: LOKI_URL\n\
          \      value: {{ .Values.global.prometheus.loki_url }}\n\
          ",
        image: {
          registry: "ghcr.io",
          repository: "d4rkfella/artifactory-pro",
          tag: "7.133.16@sha256:3eff7b8a597bf836d7ae5ed80cd18d0bd87ba1eab0d1f7caeec068e477ff7255",
          pullPolicy: "IfNotPresent",
        },
        persistence: {
          size: "200Gi",
        },
        customVolumes: "\
           - name: nfs-backup-volume\n\
          \  nfs:\n\
          \    server: 192.168.91.40\n\
          \    path: /mnt/exos20/artifactory-backup\n\
          ",
        customVolumeMounts: "\
           - name: nfs-backup-volume\n\
          \  mountPath: /mnt/artifactory-backup\n\
          ",
        haBackupDir: {
          enabled: true,
          path: "/mnt/artifactory-backup",
        },
        extraSystemYaml: {
          artifactory: {
            tomcat: {
              httpsConnector: {
                enabled: true,
              },
            },
          },
        },
        masterKeySecretName: "artifactory-secret",
        joinKeySecretName: "artifactory-secret",
        admin: {
          secret: "artifactory-secret",
          dataKey: "bootstrap.creds",
        },
      },
      postgresql: {
        enabled: false,
      },
      database: {
        type: "postgresql",
        driver: "org.postgresql.Driver",
        secrets: {
          user: {
            name: "artifactory-secret",
            key: "db-user",
          },
          password: {
            name: "artifactory-secret",
            key: "db-password",
          },
          url: {
            name: "artifactory-secret",
            key: "db-url",
          },
        },
      },
      nginx: {
        enabled: false,
      },
      additionalResources: "\
         apiVersion: v1\n\
         kind: Service\n\
         metadata:\n\
        \  name: {{ template \"artifactory.fullname\" . }}-metrics\n\
        \  annotations:\n\
        \    prometheus.io/path: \"/metrics\"\n\
        \    prometheus.io/scheme: \"http\"\n\
        \    prometheus.io/port: \"24231\"\n\
        \    prometheus.io/scrape: \"true\"\n\
        \  labels:\n\
        \    app: {{ template \"artifactory.name\" . }}\n\
        \    component: {{ template \"artifactory.name\" . }}\n\
        \    chart: {{ template \"artifactory.chart\" . }}\n\
        \    heritage: {{ .Release.Service }}\n\
        \    release: {{ .Values.global.prometheus.release_name }}\n\
         spec:\n\
        \  type: ClusterIP\n\
        \  ports:\n\
        \  - name: metrics\n\
        \    port: 24231\n\
        \    protocol: TCP\n\
        \  selector:\n\
        \    app: {{ template \"artifactory.name\" . }}\n\
        \    component: {{ template \"artifactory.name\" . }}\n\
         ---\n\
         apiVersion: monitoring.coreos.com/v1\n\
         kind: ServiceMonitor\n\
         metadata:\n\
        \  name: servicemonitor-{{ template \"artifactory.name\" . }}\n\
        \  labels:\n\
        \    metrics: jfrog\n\
        \    app: {{ template \"artifactory.name\" . }}\n\
        \    chart: {{ template \"artifactory.chart\" . }}\n\
        \    heritage: {{ .Release.Service }}\n\
        \    release: {{ .Values.global.prometheus.release_name }}\n\
         spec:\n\
        \  selector:\n\
        \    matchLabels:\n\
        \      app: {{ template \"artifactory.name\" . }}\n\
        \      component: {{ template \"artifactory.name\" . }}\n\
        \  endpoints:\n\
        \  - port: metrics\n\
        \    interval: 15s\n\
        ",
    },
  },
}
