---
{
  apiVersion: "kustomize.config.k8s.io/v1beta1",
  kind: "Kustomization",
  resources: [
    "./certificate.yaml",
    "./externalsecret.yaml",
    "./ocirepository.yaml",
    "./configmap.yaml",
    "./helmrelease.yaml",
    "./grafanadashboard.yaml",
    "./clienttrafficpolicy.yaml",
  ],
}
