---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: artifactory
spec:
  interval: 1h
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 107.133.12
  url: oci://ghcr.io/d4rkfella/charts-mirror/artifactory
  verify:
    provider: cosign
    matchOIDCIdentity:
    - issuer: https://token.actions.githubusercontent.com
      subject: https://github.com/d4rkfella/charts-mirror/.github/workflows/release.yaml@refs/heads/main
