---
# yaml-language-server: $schema=https://51f35e2d.kubernetes-schemas-9iu.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
{
  apiVersion: "helm.toolkit.fluxcd.io/v2",
  kind: "HelmRelease",
  metadata: {
    name: "zfs-scrubber",
  },
  spec: {
    interval: "1h",
    chartRef: {
      kind: "OCIRepository",
      name: "zfs-scrubber",
    },
    values: {
      controllers: {
        zfs-scrubber: {
          type: "cronjob",
          cronjob: {
            schedule: "0 0 1,15 * *",
            successfulJobsHistory: 1,
            failedJobsHistory: 1,
            concurrencyPolicy: "Forbid",
            timeZone: "Europe/Sofia",
            backoffLimit: 0,
          },
          containers: {
            app: {
              image: {
                repository: "ghcr.io/heavybullets8/zfs-scrubber",
                tag: "1.1.1@sha256:d5c3fd2edfa5fa2b054e24411d79ecbe7bd6bd76547ff59e08ae2926338a2ddd",
              },
              env: {
                ZFS_POOL: "ssd_pool",
                PUSHOVER_NOTIFICATION: true,
                TALOS_VERSION: "${TALOS_VERSION}",
              },
              envFrom: [{
                secretRef: {
                  name: "zfs-scrubber-secret",
                },
              }],
              securityContext: {
                privileged: true,
              },
            },
          },
        },
      },
      persistence: {
        dev: {
          type: "hostPath",
          hostPath: "/dev/zfs",
          globalMounts: [{
            path: "/dev/zfs",
          }],
        },
      },
    },
  },
}
