---
# yaml-language-server: $schema=https://51f35e2d.kubernetes-schemas-9iu.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
{
  apiVersion: "helm.toolkit.fluxcd.io/v2",
  kind: "HelmRelease",
  metadata: {
    name: "nvidia-device-plugin",
  },
  spec: {
    interval: "1h",
    chartRef: {
      kind: "OCIRepository",
      name: "nvidia-device-plugin",
    },
    values: {
      runtimeClassName: "nvidia",
      gfd: {
        enabled: true,
      },
      nfd: {
        enableNodeFeatureApi: true,
        worker: {
          config: {
            sources: {
              pci: {
                deviceClassWhitelist: [
                  "03",
                ],
              },
            },
          },
        },
      },
    },
  },
}
