---
# yaml-language-server: $schema=https://51f35e2d.kubernetes-schemas-9iu.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
{
  apiVersion: "helm.toolkit.fluxcd.io/v2",
  kind: "HelmRelease",
  metadata: {
    name: "smartctl-exporter",
  },
  spec: {
    interval: "1h",
    chartRef: {
      kind: "OCIRepository",
      name: "prometheus-smartctl-exporter",
    },
    driftDetection: {
      mode: "enabled",
      ignore: [
        # Ignore "validated" annotation which is not inserted during install
        {
          paths: [
            "/metadata/annotations/prometheus-operator-validated",
          ],
          target: {
            kind: "PrometheusRule",
          },
        },
      ],
    },
    values: {
      fullnameOverride: "smartctl-exporter",
      serviceMonitor: {
        enabled: true,
      },
      prometheusRules: {
        enabled: false,
      },
      image: {
        repository: "ghcr.io/d4rkfella/smartctl_exporter",
        tag: "0.14.0@sha256:bf5b9d254f17b9497289f6d1d4d64dc8ede1feaf2b1eae945030c48340e1b60e",
      },
    },
  },
}
