---
# yaml-language-server: $schema=https://kubernetes-schemas-9iu.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: multus
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: multus
  values:
    cniPlugins:
      image:
        repository: ghcr.io/d4rkfella/cni-plugins
        tag: 1.9.1@sha256:33a1a3be64d20aca8828b57c669ad8cc5cafa29588450b98477e39dafa5dcaa2
    image:
      repository: ghcr.io/d4rkfella/multus-cni
      tag: 4.3.1@sha256:c32acb3f0c0e988d9229ecd81602775e21a98fcf341039ae746dff748ced3699
    resources:
      requests:
        cpu: 10m
      limits:
        memory: 512Mi
