---
# yaml-language-server: $schema=https://51f35e2d.kubernetes-schemas-9iu.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
{
  apiVersion: "helm.toolkit.fluxcd.io/v2",
  kind: "HelmRelease",
  metadata: {
    name: "multus",
  },
  spec: {
    interval: "1h",
    chartRef: {
      kind: "OCIRepository",
      name: "multus",
    },
    postRenderers: [{
      kustomize: {
        patches: [{
          target: {
            kind: "DaemonSet",
            name: "multus",
          },
          patch: "\
             - op: add\n\
            \  path: /spec/template/spec/containers/0/args\n\
            \  value:\n\
            \    - \"--cleanup-config-on-exit\"\n\
            \    - \"--multus-bin-file=/usr/bin/multus\"\n\
            \    - \"--multus-cni-conf-dir=/tmp\"\n\
            ",
        }],
      },
    }],
    values: {
      cni-plugins: {
        image: {
          repository: "ghcr.io/d4rkfella/cni-plugins",
          tag: "1.9.1@sha256:72ad24452cd6ab855cc76b7af828d13696b016af21c2b31d3d4705b892302dda",
        },
        resources: {},
      },
      multus: {
        image: {
          repository: "ghcr.io/d4rkfella/multus-cni",
          tag: "4.2.4@sha256:13b6c5f52121f29ba968bb7436c9813546c85c88342b6d4524433c74b722a5d9",
        },
        resources: {
          requests: {
            cpu: "10m",
          },
          limits: {
            memory: "512Mi",
          },
        },
      },
      cni: {
        netPath: "/etc/cni/net.d",
        binPath: "/opt/cni/bin",
      },
    },
  },
}
