---
# yaml-language-server: $schema=https://kubernetes-schemas-9iu.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: multus
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: multus
  values:
    cniPlugins:
      image:
        repository: ghcr.io/d4rkfella/cni-plugins
        tag: 1.9.1@sha256:38c7f84275389ccc560da51d0f2c57d1f0c2ba81d9b97d823703b189322ec373
    image:
      repository: ghcr.io/d4rkfella/multus-cni
      tag: 4.3.1@sha256:031bc2a509527210cab1ad580173172d21f455b78bcd3e8d22a95d1ea8d9cec8
    resources:
      requests:
        cpu: 10m
      limits:
        memory: 512Mi
