---
{
  apiVersion: "v1",
  kind: "ConfigMap",
  metadata: {
    name: "collabora-custom-css",
  },
  data: {
    branding-desktop.css: "\
       :root {\n\
      \    --color-box-shadow: rgba(0, 0, 0, 0.1);\n\
      \    --header-font-size: 13px;\n\
      \    --btn-size: 25px;\n\
      \    --color-border: #d1d1d1;\n\
      \    --color-primary: #2399f4;\n\
      \    --co-border-radius: 4px;\n\
      \    --color-main-background: #f5f5f5;\n\
      \    --color-background-dark: #f5f5f5;\n\
      \    --color-background-darker: #f5f5f5;\n\
      \    --color-btn-border: transparent;\n\
      \    --co-color-border-dark: #fafafa;\n\
      \    --header-height: 35px;\n\
      \    --color-border-darker: transparent;\n\
      \    --color-border-dark: transparent;\n\
      \    --color-main-text: #454545;\n\
      \    --color-text-darker: #444;\n\
      \    --tb-min-fs: 13.5px;\n\
      \    --tb-max-fs: 13.5px;\n\
      \    --btn-padding: 3px;\n\
      \    --jquery-ui-font: system-ui, sans-serif;\n\
       }\n\
       \n\
       #document-header, #save,\n\
       #toggleuimode-button, #optionstoolboxdown, #toggledarktheme-button,\n\
       #home-reset-attributes, #zoomreset,\n\
       #latestupdates {\n\
      \    display: none !important;\n\
       }\n\
       \n\
       button#home-brush-button,\n\
       button#home-reset-attributes {\n\
      \    display: none;\n\
       }\n\
       \n\
       #document-name-input {\n\
      \    display: none !important;\n\
       }\n\
       \n\
       .ui-scroll-left,\n\
       .ui-scroll-right {\n\
      \    opacity: 0.1;\n\
      \    filter: grayscale(1);\n\
       }\n\
       \n\
       #toolbar-wrapper {\n\
      \    border: none;\n\
      \    background: var(--color-main-background) !important;\n\
      \    padding: 0 !important;\n\
       }\n\
       \n\
       #toolbar-row {\n\
      \    background: white;\n\
      \    margin: 10px 10px 0 10px;\n\
      \    border-radius: 5px;\n\
      \    margin-top: 0;\n\
      \    padding: 5px;\n\
      \    box-shadow: 0 0 3px rgba(0, 0, 0, 0.05);\n\
       }\n\
       \n\
       #toolbar-up .ui-tab.selected.notebookbar {\n\
      \    font-weight: bolder;\n\
       }\n\
       \n\
       .ui-listbox-arrow {\n\
      \    opacity: 0.5;\n\
      \    transform: scale(0.8);\n\
       }\n\
       \n\
       #sidebar-dock-wrapper {\n\
      \    background: var(--color-main-background);\n\
      \    padding-top: 20px !important;\n\
       }\n\
       \n\
       .cooltip-text {\n\
      \    background: white;\n\
      \    color: #666;\n\
      \    padding: 2px 10px;\n\
      \    font-size: 0.75rem;\n\
      \    border-radius: 3px;\n\
      \    border: 1px solid rgba(0, 0, 0, 0.04);\n\
       }\n\
      ",
  },
}
