---
{
  # yaml-language-server: $schema=https://51f35e2d.kubernetes-schemas-9iu.pages.dev/generators.external-secrets.io/clustergenerator_v1alpha1.json
  apiVersion: "generators.external-secrets.io/v1alpha1",
  kind: "ClusterGenerator",
  metadata: {
    name: "collabora-proof-key",
  },
  spec: {
    kind: "SSHKey",
    generator: {
      sshKeySpec: {
        keyType: "rsa",
        keySize: 4096,
        comment: "collabora-proof-key",
      },
    },
  },
}
---
{
  # yaml-language-server: $schema=https://51f35e2d.kubernetes-schemas-9iu.pages.dev/external-secrets.io/externalsecret_v1.json
  apiVersion: "external-secrets.io/v1",
  kind: "ExternalSecret",
  metadata: {
    name: "collabora-proof-key",
  },
  spec: {
    secretStoreRef: {
      kind: "ClusterSecretStore",
      name: "hashicorp-vault",
    },
    target: {
      name: "collabora-proof-key",
    },
    dataFrom: [{
      sourceRef: {
        generatorRef: {
          apiVersion: "generators.external-secrets.io/v1alpha1",
          kind: "ClusterGenerator",
          name: "collabora-proof-key",
        },
      },
    }],
  },
}
---
{
  # yaml-language-server: $schema=https://51f35e2d.kubernetes-schemas-9iu.pages.dev/external-secrets.io/externalsecret_v1.json
  apiVersion: "external-secrets.io/v1",
  kind: "ExternalSecret",
  metadata: {
    name: "collabora-credentials",
  },
  spec: {
    secretStoreRef: {
      kind: "ClusterSecretStore",
      name: "hashicorp-vault",
    },
    target: {
      name: "collabora-credentials",
    },
    dataFrom: [{
      extract: {
        key: "secrets/collabora",
      },
    }],
  },
}
