---
# yaml-language-server: $schema=https://51f35e2d.kubernetes-schemas-9iu.pages.dev/external-secrets.io/externalsecret_v1beta1.json
{
  apiVersion: "external-secrets.io/v1",
  kind: "ExternalSecret",
  metadata: {
    name: "autobrr",
  },
  spec: {
    secretStoreRef: {
      kind: "ClusterSecretStore",
      name: "hashicorp-vault",
    },
    target: {
      name: "autobrr-secret",
      template: {
        data: {
          AUTOBRR__SESSION_SECRET: "{{ .SESSION_SECRET }}",
          AUTOBRR__OIDC_CLIENT_SECRET: "{{ .CLIENT_SECRET }}",
          AUTOBRR__DATABASE_DSN: "postgresql://{{ .POSTGRES_USERNAME }}:{{ .POSTGRES_PASSWORD | urlquery }}@postgres-db-rw.database.svc.cluster.local:5432/autobrr?sslmode=verify-full&sslrootcert=/etc/ssl/certs/postgres-ca.crt",
        },
      },
    },
    dataFrom: [{
      extract: {
        key: "secrets/autobrr",
      },
    }],
  },
}
