---
# yaml-language-server: $schema=https://kubernetes-schemas-9iu.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: pgadmin
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: pgadmin
  values:
    controllers:
      pgadmin:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          pgadmin:
            image:
              repository: ghcr.io/d4rkfella/pgadmin4
              tag: 9.18@sha256:a470c3fe3eab6eab8fe4a7959ecfa30430b3688b84ae3763d3d8639f1cc7c304
            env:
              GUNICORN_LIMIT_REQUEST_LINE: 0
              GUNICORN_LIMIT_REQUEST_FIELD_SIZE: 0
              PGADMIN_AUTHENTICATION_SOURCES: "['oauth2']"
              PGADMIN_MASTER_PASSWORD_REQUIRED: "True"
              PGADMIN_OAUTH2_DISPLAY_NAME: Keycloak
              PGADMIN_OAUTH2_NAME: keycloak
              PGADMIN_OAUTH2_SERVER_METADATA_URL: https://accounts.darkfellanetwork.com/realms/DarkfellaNET/.well-known/openid-configuration
              PGADMIN_OAUTH2_USERNAME_CLAIM: preferred_username
              PGADMIN_OAUTH2_CHALLENGE_METHOD: S256
              PGADMIN_OAUTH2_RESPONSE_TYPE: code
              PGADMIN_OAUTH2_CLIENT_ID: 1935675b-bf31-48f2-9290-80ae2394ac07
              PGADMIN_OAUTH2_LOGOUT_URL: https://accounts.darkfellanetwork.com/realms/DarkfellaNET/protocol/openid-connect/logout?post_logout_redirect_uri={redirect_uri}&id_token_hint={id_token}
            envFrom:
              - secretRef:
                  name: pgadmin-secret
            securityContext:
              allowPrivilegeEscalation: false
              capabilities:
                drop:
                  - ALL
              readOnlyRootFilesystem: true
    defaultPodOptions:
      hostUsers: false
      securityContext:
        runAsNonRoot: true
        runAsUser: 65532
        runAsGroup: 65532
        fsGroup: 65532
        fsGroupChangePolicy: OnRootMismatch
        seccompProfile:
          type: RuntimeDefault
    persistence:
      config:
        existingClaim: "{{ .Release.Name }}"
        globalMounts:
          - path: /var/lib/pgadmin
      empty:
        type: emptyDir
        sizeLimit: 100Mi
        globalMounts:
          - path: /tmp
            subPath: tmp
          - path: /var/log
            subPath: log
    route:
      pgadmin:
        hostnames:
          - "{{ .Release.Name }}.darkfellanetwork.com"
        parentRefs:
          - name: internal
            namespace: envoy-gateway-system
        rules:
          - backendRefs:
              - port: 80
                name: pgadmin
    service:
      pgadmin:
        controller: pgadmin
        ports:
          http:
            port: 80
