---
{
  apiVersion: "batch/v1",
  kind: "CronJob",
  metadata: {
    name: "vaultbackup",
  },
  spec: {
    concurrencyPolicy: "Forbid",
    schedule: "0 7 * * *",
    jobTemplate: {
      spec: {
        backoffLimit: 3,
        template: {
          spec: {
            serviceAccountName: "vault",
            containers: [{
              name: "vaultctl",
              image: "ghcr.io/d4rkfella/vaultctl:0.2.3@sha256:4e623b2e146d0f8d828a8c0e189f134c3d504def3dc4abc53a7b3a49ac812c42",
              imagePullPolicy: "IfNotPresent",
              args: [
                "backup-raft-snapshot",
                "--to",
                "s3://hashicorp-vault-backup/"
              ],
              env: [{
                name: "VAULT_ADDR",
                value: "https://vault.darkfellanetwork.com:8200",
              }, {
                name: "VAULT_K8S_ROLE",
                value: "vault",
              }, {
                name: "AWS_ENDPOINT_URL",
                value: "https://2bd80478faceecf0d53c596cd910805f.r2.cloudflarestorage.com",
              }],
              envFrom: [{
                secretRef: {
                  name: "vault-backup-secret",
                },
              }],
              securityContext: {
                allowPrivilegeEscalation: false,
                readOnlyRootFilesystem: true,
                capabilities: {
                  drop: [
                    "ALL",
                  ],
                },
              },
              resources: {
                limits: {
                  cpu: "1",
                  memory: "1.5Gi",
                },
                requests: {
                  cpu: "500m",
                  memory: "1Gi",
                },
              },
            }],
            restartPolicy: "OnFailure",
            securityContext: {
              runAsNonRoot: true,
              runAsUser: 65532,
              runAsGroup: 65532,
              seccompProfile: {
                type: "RuntimeDefault",
              },
            },
          },
        },
      },
    },
    successfulJobsHistoryLimit: 1,
    failedJobsHistoryLimit: 1,
  },
}
