---
{
  apiVersion: "monitoring.coreos.com/v1",
  kind: "ServiceMonitor",
  metadata: {
    name: "vault",
  },
  spec: {
    selector: {
      matchLabels: {
        vault-internal: "true",
      },
    },
    namespaceSelector: {
      matchNames: [
        "vault",
      ],
    },
    endpoints: [{
      interval: "30s",
      path: "/v1/sys/metrics",
      params: {
        format: [
          "prometheus",
        ],
      },
      port: "https",
      scheme: "https",
      scrapeTimeout: "30s",
      bearerTokenFile: "/vault/secrets/token",
      tlsConfig: {
        insecureSkipVerify: false,
        serverName: "vault.darkfellanetwork.com",
      },
    }],
  },
}
