---
{
  # yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
  apiVersion: "helm.toolkit.fluxcd.io/v2",
  kind: "HelmRelease",
  metadata: {
    name: "gpu-operator",
  },
  spec: {
    interval: "1h",
    chartRef: {
      kind: "OCIRepository",
      name: "gpu-operator",
    },
    values: {
      dcgmExporter: {
        env: [{
          name: "KUBERNETES_VIRTUAL_GPUS",
          value: "true",
        }],
        serviceMonitor: {
          enabled: true,
          honorLabels: true,
          relabelings: [{
            sourceLabels: [
              "__meta_kubernetes_pod_node_name",
            ],
            regex: "(.*)",
            targetLabel: "instance",
            replacement: "$1",
            action: "replace",
          }],
        },
      },
      driver: {
        enabled: false,
      },
      toolkit: {
        enabled: false,
      },
      migManager: {
        enabled: false,
      },
      operator: {
        defaultRuntime: "containerd",
      },
      sandboxDevicePlugin: {
        enabled: false,
      },
      vfioManager: {
        enabled: false,
      },
      vgpuDeviceManager: {
        enabled: false,
      },
      hostPaths: {
        driverInstallDir: "/usr/local/glibc/usr/lib",
      },
      node-feature-discovery: {
        worker: {
          config: {
            sources: {
              custom: [{
                name: "talos-os-version-fix",
                labels: {
                  feature.node.kubernetes.io/system-os_release.VERSION_ID: "1.13",
                },
                matchFeatures: [{
                  feature: "node.kubernetes.io/system-os_release",
                  matchExpressions: {
                    ID: {
                      op: "In",
                      value: [
                        "talos",
                      ],
                    },
                  },
                }],
              }],
            },
          },
        },
      },
    },
  },
}
