---
{
  # yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
  apiVersion: "helm.toolkit.fluxcd.io/v2",
  kind: "HelmRelease",
  metadata: {
    name: "gpu-operator",
  },
  spec: {
    interval: "1h",
    chartRef: {
      kind: "OCIRepository",
      name: "gpu-operator",
    },
    values: {
      dcgmExporter: {
        env: [{
          name: "KUBERNETES_VIRTUAL_GPUS",
          value: "true",
        }],
        serviceMonitor: {
          enabled: true,
          honorLabels: true,
          relabelings: [{
            sourceLabels: [
              "__meta_kubernetes_pod_node_name",
            ],
            regex: "(.*)",
            targetLabel: "instance",
            replacement: "$1",
            action: "replace",
          }],
        },
      },
      driver: {
        enabled: false,
      },
      toolkit: {
        enabled: false,
      },
      hostPaths: {
        driverInstallDir: "/usr/local/glibc/usr/lib",
      },
    },
    postRenderers: [{
      kustomize: {
        patches: [{
          patch: "\
             apiVersion: apps/v1\n\
             kind: Deployment\n\
             metadata:\n\
            \  name: gpu-operator\n\
            \  labels:\n\
            \    app.kubernetes.io/component: \"gpu-operator\"\n\
             spec:\n\
            \  template:\n\
            \    spec:\n\
            \      containers:\n\
            \        - name: gpu-operator\n\
            \          securityContext:\n\
            \            allowPrivilegeEscalation: false\n\
            \            capabilities: { drop: [\"ALL\"] }\n\
            \            readOnlyRootFilesystem: true\n\
            \            runAsNonRoot: true\n\
            \            runAsUser: 65532\n\
            \            runAsGroup: 65532\n\
            \      securityContext:\n\
            \        fsGroup: 65532\n\
            \        fsGroupChangePolicy: OnRootMismatch\
            ",
        }],
      },
    }],
  },
}
