---
# yaml-language-server: $schema=https://51f35e2d.kubernetes-schemas-9iu.pages.dev/source.toolkit.fluxcd.io/ocirepository_v1.json
{
  apiVersion: "source.toolkit.fluxcd.io/v1",
  kind: "OCIRepository",
  metadata: {
    name: "gpu-operator",
  },
  spec: {
    interval: "15m",
    layerSelector: {
      mediaType: "application/vnd.cncf.helm.chart.content.v1.tar+gzip",
      operation: "copy",
    },
    ref: {
      tag: "v26.3.1",
    },
    url: "oci://ghcr.io/d4rkfella/charts-mirror/gpu-operator",
    verify: {
      provider: "cosign",
      matchOIDCIdentity: [{
        issuer: "https://token.actions.githubusercontent.com",
        subject: "https://github.com/d4rkfella/charts-mirror/.github/workflows/chart-builder.yaml@refs/heads/main",
      }],
    },
  },
}
