---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: cilium-network-policy-pod-alert
spec:
  groups:
    - name: cilium.rules
      rules:
        - alert: CiliumNetworkPolicyBlocked
          expr: |
            sum by (
              source_namespace,
              source_workload,
              destination_namespace,
              destination_workload,
              reason
            ) (
              rate(hubble_drop_total{reason="POLICY_DENIED"}[5m])
            ) > 0
          for: 5m
          labels:
            severity: warning
          annotations:
            summary: Cilium blocked traffic due to NetworkPolicy
            description: |-
              Traffic from {{ $labels.source_namespace }}/{{ $labels.source_workload }} to {{ $labels.destination_namespace }}/{{ $labels.destination_workload }} is being dropped due to {{ $labels.reason }}.
