---
# yaml-language-server: $schema=https://51f35e2d.kubernetes-schemas-9iu.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
{
  apiVersion: "kustomize.toolkit.fluxcd.io/v1",
  kind: "Kustomization",
  metadata: {
    name: "keycloak-instance",
  },
  spec: {
    dependsOn: [{
      name: "cloudnative-pg-cluster",
      namespace: "database",
    }, {
      name: "keycloak-operator",
    }],
    healthChecks: [{
      apiVersion: "k8s.keycloak.org/v2alpha1",
      kind: "Keycloak",
      name: "keycloak",
      namespace: "keycloak",
    }, {
      apiVersion: "gateway.networking.k8s.io/v1",
      kind: "HTTPRoute",
      name: "keycloak",
      namespace: "keycloak",
    }],
    healthCheckExprs: [{
      apiVersion: "k8s.keycloak.org/v2alpha1",
      kind: "Keycloak",
      failed: "status.conditions.filter(e, e.type == 'Ready').all(e, e.status == 'False')",
      current: "status.conditions.filter(e, e.type == 'Ready').all(e, e.status == 'True')",
    }, {
      apiVersion: "gateway.networking.k8s.io/v1",
      kind: "HTTPRoute",
      current: "status.parents.exists(p, p.conditions.exists(c, c.type == 'Accepted' && c.status == 'True')) && status.parents.exists(p, p.conditions.exists(c, c.type == 'ResolvedRefs' && c.status == 'True'))",
      failed: "status.parents.exists(p, p.conditions.exists(c, c.type == 'Accepted' && c.status == 'False')) || status.parents.exists(p, p.conditions.exists(c, c.type == 'ResolvedRefs' && c.status == 'False'))",
    }],
    path: "./kubernetes/apps/keycloak/keycloak-instance/manifests",
    prune: true,
    sourceRef: {
      kind: "GitRepository",
      name: "flux-system",
      namespace: "flux-system",
    },
    interval: "1h",
  },
}
